export enum Pattern {
  P1_PASSIVE_LISTENER = 'P1_PASSIVE_LISTENER',
  P2_SCHEDULED_ACTION = 'P2_SCHEDULED_ACTION',
  P3_INFO_PROVIDER = 'P3_INFO_PROVIDER',
  P4_CLAIM_ACTION = 'P4_CLAIM_ACTION',
  P5_IDENTITY_MUTATION = 'P5_IDENTITY_MUTATION',
  P6_GLOBAL_RULE = 'P6_GLOBAL_RULE',
  P7_SPEECH_ENFORCEMENT = 'P7_SPEECH_ENFORCEMENT',
  P8_SETUP_CONSTRAINT = 'P8_SETUP_CONSTRAINT'
}

export const MOMENT_TYPES = [
  'MOMENT_GAME_STARTED',
  'MOMENT_SETUP_STARTED',
  'MOMENT_SETUP_FINISHED',
  'MOMENT_NIGHT_STARTED',
  'MOMENT_BEFORE_WAKE',
  'MOMENT_AFTER_WAKE',
  'MOMENT_PUT_TO_SLEEP',
  'MOMENT_NIGHT_ENDED',
  'MOMENT_DAY_STARTED',
  'MOMENT_DUSK',
  'MOMENT_DAY_ENDED',
  'MOMENT_CLAIM',
  'MOMENT_CLAIMED',
  'MOMENT_NOMINATION_STARTED',
  'MOMENT_NOMINATION_CANCELLED',
  'MOMENT_VOTE_STARTED',
  'MOMENT_VOTE_CAST',
  'MOMENT_VOTE_RESOLVED',
  'MOMENT_EXECUTION_STARTED',
  'MOMENT_EXECUTION_RESOLVED',
  'MOMENT_DEATH_ATTEMPTED',
  'MOMENT_DEATH_RESOLVED',
  'PLAYER_REVIVED',
  'ROLE_CHANGED',
  'ALIGNMENT_CHANGED',
  'SHOWN_ROLE_CHANGED',
  'PRIVATE_INFO_DELIVERED',
  'PUBLIC_ANNOUNCEMENT',
  'GAME_ENDED'
] as const

export type MomentType = (typeof MOMENT_TYPES)[number]

export const EFFECT_TYPES = [
  'DEAD',
  'APPEARS_DEAD',
  'POISONED',
  'DRUNK',
  'PROTECTED',
  'IMMUNE_ONCE',
  'REDIRECT_KILL',
  'MARKED_FOR_DEATH',
  'VOTE_WEIGHT',
  'VOTE_LOCKED',
  'VOTE_HIDDEN',
  'CANNOT_NOMINATE',
  'MUST_NOMINATE',
  'EXTRA_NOMINATION',
  'GRIMOIRE_VIEW_GRANTED',
  'EVIL_TEAM_INFO_BLOCKED',
  'BLUFFS_ASSIGNED',
  'SECRET_MINION',
  'DEMON_HOLDER',
  'NO_ABILITY',
  'SECONDARY_ABILITY_GRANTED',
  'ABILITY_DISABLED',
  'MADNESS',
  'SILENCED',
  'FORBIDDEN_PHRASE',
  'GLOBAL_RULE_ACTIVE',
  'LINKED_PAIR',
  'HOSTED_BY',
  'DEAD_ACTS'
] as const

export type EffectType = (typeof EFFECT_TYPES)[number]

export const GLOBAL_RULE_KEYS = [
  'VORTOX',
  'LEVIATHAN',
  'LEGION',
  'RIOT',
  'ATHEIST',
  'HERETIC',
  'POPPY_GROWER',
  'BOOTLEGGER',
  'LIL_MONSTA',
  'XAAN',
  'ZENOMANCER',
  'YAGGABABBLE'
] as const

export type GlobalRuleKey = (typeof GLOBAL_RULE_KEYS)[number]

export type ClaimKind = string

export const CLAIM_KIND_SUGGESTIONS = [
  'CLAIM/DEFAULT',
  'CLAIM/QUESTION',
  'CLAIM/GUESS',
  'CLAIM/ALTERNATE',
  'CLAIM/SECRET'
] as const

export function namespaceClaimKind(roleKey: string, suffix: string | undefined): ClaimKind {
  const cleanSuffix = suffix && suffix.trim().length > 0 ? `/${suffix.trim().toUpperCase()}` : ''
  return `CLAIM/${roleKey.toUpperCase()}${cleanSuffix}`
}
