/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GameRouteImport } from './routes/game'
import { Route as UnauthedRouteImport } from './routes/_unauthed'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed.index'
import { Route as GamesGameIdRouteImport } from './routes/games/$gameId'
import { Route as GameGrimRouteImport } from './routes/game/grim'
import { Route as ApiWhoamiRouteImport } from './routes/api/whoami'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as UnauthedLogoutRouteImport } from './routes/_unauthed.logout'
import { Route as UnauthedLoginRouteImport } from './routes/_unauthed.login'
import { Route as UnauthedAboutRouteImport } from './routes/_unauthed.about'
import { Route as AuthedScriptsRouteImport } from './routes/_authed.scripts'
import { Route as ApiScriptsIndexRouteImport } from './routes/api/scripts/index'
import { Route as ApiRoomsIndexRouteImport } from './routes/api/rooms/index'
import { Route as ApiInvitesIndexRouteImport } from './routes/api/invites/index'
import { Route as AuthedRoomsIndexRouteImport } from './routes/_authed.rooms.index'
import { Route as GameGrimWindowRouteImport } from './routes/game/grim/window'
import { Route as ApiDevGrimoireRouteImport } from './routes/api/dev/grimoire'
import { Route as ApiAuthSettingsRouteImport } from './routes/api/auth/settings'
import { Route as ApiAuthRegisterRouteImport } from './routes/api/auth/register'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthForgotPasswordRouteImport } from './routes/api/auth/forgot-password'
import { Route as AuthedScriptsNRouteImport } from './routes/_authed.scripts.n'
import { Route as AuthedRoomsNRouteImport } from './routes/_authed.rooms.n'
import { Route as AuthedAuthForgotPasswordRouteImport } from './routes/_authed.auth.forgot-password'
import { Route as ApiRoomsRoomIdIndexRouteImport } from './routes/api/rooms/$roomId/index'
import { Route as ApiMatchesMatchIdIndexRouteImport } from './routes/api/matches/$matchId/index'
import { Route as ApiRoomsRoomIdStartMatchRouteImport } from './routes/api/rooms/$roomId/start-match'
import { Route as ApiRoomsRoomIdScriptRouteImport } from './routes/api/rooms/$roomId/script'
import { Route as ApiRoomsRoomIdRemovePlayerRouteImport } from './routes/api/rooms/$roomId/remove-player'
import { Route as ApiRoomsRoomIdMatchRouteImport } from './routes/api/rooms/$roomId/match'
import { Route as ApiRoomsRoomIdInvitesRouteImport } from './routes/api/rooms/$roomId/invites'
import { Route as ApiRoomsRoomIdEmptySeatRouteImport } from './routes/api/rooms/$roomId/empty-seat'
import { Route as ApiMatchesMatchIdTravelRequestRouteImport } from './routes/api/matches/$matchId/travel-request'
import { Route as ApiMatchesMatchIdTravelDenyRouteImport } from './routes/api/matches/$matchId/travel-deny'
import { Route as ApiMatchesMatchIdTravelApproveRouteImport } from './routes/api/matches/$matchId/travel-approve'
import { Route as ApiMatchesMatchIdPhaseRouteImport } from './routes/api/matches/$matchId/phase'
import { Route as ApiInvitesInviteIdRejectRouteImport } from './routes/api/invites/$inviteId/reject'
import { Route as ApiInvitesInviteIdCancelRouteImport } from './routes/api/invites/$inviteId/cancel'
import { Route as ApiInvitesInviteIdAcceptRouteImport } from './routes/api/invites/$inviteId/accept'
import { Route as ApiGamesGameIdWhispersRouteImport } from './routes/api/games/$gameId/whispers'
import { Route as ApiGamesGameIdStorytellersRouteImport } from './routes/api/games/$gameId/storytellers'
import { Route as ApiGamesGameIdStartSetupRouteImport } from './routes/api/games/$gameId/start-setup'
import { Route as ApiGamesGameIdReadyRouteImport } from './routes/api/games/$gameId/ready'
import { Route as ApiGamesGameIdHostRouteImport } from './routes/api/games/$gameId/host'
import { Route as ApiAuthMeModRouteImport } from './routes/api/auth/me/mod'
import { Route as AuthedRoomsRoomRoomIdIndexRouteImport } from './routes/_authed.rooms._room.$roomId.index'
import { Route as AuthedRoomsRoomRoomIdStRouteImport } from './routes/_authed.rooms._room.$roomId._st'
import { Route as AuthedRoomsRoomRoomIdStWindowRouteImport } from './routes/_authed.rooms._room.$roomId._st.window'

const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthedRoute = UnauthedRouteImport.update({
  id: '/_unauthed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const GamesGameIdRoute = GamesGameIdRouteImport.update({
  id: '/games/$gameId',
  path: '/games/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const GameGrimRoute = GameGrimRouteImport.update({
  id: '/grim',
  path: '/grim',
  getParentRoute: () => GameRoute,
} as any)
const ApiWhoamiRoute = ApiWhoamiRouteImport.update({
  id: '/api/whoami',
  path: '/api/whoami',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthedLogoutRoute = UnauthedLogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => UnauthedRoute,
} as any)
const UnauthedLoginRoute = UnauthedLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => UnauthedRoute,
} as any)
const UnauthedAboutRoute = UnauthedAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => UnauthedRoute,
} as any)
const AuthedScriptsRoute = AuthedScriptsRouteImport.update({
  id: '/scripts',
  path: '/scripts',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiScriptsIndexRoute = ApiScriptsIndexRouteImport.update({
  id: '/api/scripts/',
  path: '/api/scripts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoomsIndexRoute = ApiRoomsIndexRouteImport.update({
  id: '/api/rooms/',
  path: '/api/rooms/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInvitesIndexRoute = ApiInvitesIndexRouteImport.update({
  id: '/api/invites/',
  path: '/api/invites/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoomsIndexRoute = AuthedRoomsIndexRouteImport.update({
  id: '/rooms/',
  path: '/rooms/',
  getParentRoute: () => AuthedRoute,
} as any)
const GameGrimWindowRoute = GameGrimWindowRouteImport.update({
  id: '/window',
  path: '/window',
  getParentRoute: () => GameGrimRoute,
} as any)
const ApiDevGrimoireRoute = ApiDevGrimoireRouteImport.update({
  id: '/api/dev/grimoire',
  path: '/api/dev/grimoire',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSettingsRoute = ApiAuthSettingsRouteImport.update({
  id: '/api/auth/settings',
  path: '/api/auth/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRegisterRoute = ApiAuthRegisterRouteImport.update({
  id: '/api/auth/register',
  path: '/api/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthForgotPasswordRoute = ApiAuthForgotPasswordRouteImport.update({
  id: '/api/auth/forgot-password',
  path: '/api/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedScriptsNRoute = AuthedScriptsNRouteImport.update({
  id: '/n',
  path: '/n',
  getParentRoute: () => AuthedScriptsRoute,
} as any)
const AuthedRoomsNRoute = AuthedRoomsNRouteImport.update({
  id: '/rooms/n',
  path: '/rooms/n',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAuthForgotPasswordRoute =
  AuthedAuthForgotPasswordRouteImport.update({
    id: '/auth/forgot-password',
    path: '/auth/forgot-password',
    getParentRoute: () => AuthedRoute,
  } as any)
const ApiRoomsRoomIdIndexRoute = ApiRoomsRoomIdIndexRouteImport.update({
  id: '/api/rooms/$roomId/',
  path: '/api/rooms/$roomId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMatchesMatchIdIndexRoute = ApiMatchesMatchIdIndexRouteImport.update({
  id: '/api/matches/$matchId/',
  path: '/api/matches/$matchId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoomsRoomIdStartMatchRoute =
  ApiRoomsRoomIdStartMatchRouteImport.update({
    id: '/api/rooms/$roomId/start-match',
    path: '/api/rooms/$roomId/start-match',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiRoomsRoomIdScriptRoute = ApiRoomsRoomIdScriptRouteImport.update({
  id: '/api/rooms/$roomId/script',
  path: '/api/rooms/$roomId/script',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoomsRoomIdRemovePlayerRoute =
  ApiRoomsRoomIdRemovePlayerRouteImport.update({
    id: '/api/rooms/$roomId/remove-player',
    path: '/api/rooms/$roomId/remove-player',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiRoomsRoomIdMatchRoute = ApiRoomsRoomIdMatchRouteImport.update({
  id: '/api/rooms/$roomId/match',
  path: '/api/rooms/$roomId/match',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoomsRoomIdInvitesRoute = ApiRoomsRoomIdInvitesRouteImport.update({
  id: '/api/rooms/$roomId/invites',
  path: '/api/rooms/$roomId/invites',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoomsRoomIdEmptySeatRoute = ApiRoomsRoomIdEmptySeatRouteImport.update({
  id: '/api/rooms/$roomId/empty-seat',
  path: '/api/rooms/$roomId/empty-seat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMatchesMatchIdTravelRequestRoute =
  ApiMatchesMatchIdTravelRequestRouteImport.update({
    id: '/api/matches/$matchId/travel-request',
    path: '/api/matches/$matchId/travel-request',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMatchesMatchIdTravelDenyRoute =
  ApiMatchesMatchIdTravelDenyRouteImport.update({
    id: '/api/matches/$matchId/travel-deny',
    path: '/api/matches/$matchId/travel-deny',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMatchesMatchIdTravelApproveRoute =
  ApiMatchesMatchIdTravelApproveRouteImport.update({
    id: '/api/matches/$matchId/travel-approve',
    path: '/api/matches/$matchId/travel-approve',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMatchesMatchIdPhaseRoute = ApiMatchesMatchIdPhaseRouteImport.update({
  id: '/api/matches/$matchId/phase',
  path: '/api/matches/$matchId/phase',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInvitesInviteIdRejectRoute =
  ApiInvitesInviteIdRejectRouteImport.update({
    id: '/api/invites/$inviteId/reject',
    path: '/api/invites/$inviteId/reject',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInvitesInviteIdCancelRoute =
  ApiInvitesInviteIdCancelRouteImport.update({
    id: '/api/invites/$inviteId/cancel',
    path: '/api/invites/$inviteId/cancel',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInvitesInviteIdAcceptRoute =
  ApiInvitesInviteIdAcceptRouteImport.update({
    id: '/api/invites/$inviteId/accept',
    path: '/api/invites/$inviteId/accept',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGamesGameIdWhispersRoute = ApiGamesGameIdWhispersRouteImport.update({
  id: '/api/games/$gameId/whispers',
  path: '/api/games/$gameId/whispers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGamesGameIdStorytellersRoute =
  ApiGamesGameIdStorytellersRouteImport.update({
    id: '/api/games/$gameId/storytellers',
    path: '/api/games/$gameId/storytellers',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGamesGameIdStartSetupRoute =
  ApiGamesGameIdStartSetupRouteImport.update({
    id: '/api/games/$gameId/start-setup',
    path: '/api/games/$gameId/start-setup',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGamesGameIdReadyRoute = ApiGamesGameIdReadyRouteImport.update({
  id: '/api/games/$gameId/ready',
  path: '/api/games/$gameId/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGamesGameIdHostRoute = ApiGamesGameIdHostRouteImport.update({
  id: '/api/games/$gameId/host',
  path: '/api/games/$gameId/host',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeModRoute = ApiAuthMeModRouteImport.update({
  id: '/api/auth/me/mod',
  path: '/api/auth/me/mod',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoomsRoomRoomIdIndexRoute =
  AuthedRoomsRoomRoomIdIndexRouteImport.update({
    id: '/rooms/_room/$roomId/',
    path: '/rooms/$roomId/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedRoomsRoomRoomIdStRoute = AuthedRoomsRoomRoomIdStRouteImport.update({
  id: '/rooms/_room/$roomId/_st',
  path: '/rooms/$roomId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRoomsRoomRoomIdStWindowRoute =
  AuthedRoomsRoomRoomIdStWindowRouteImport.update({
    id: '/window',
    path: '/window',
    getParentRoute: () => AuthedRoomsRoomRoomIdStRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/game': typeof GameRouteWithChildren
  '/scripts': typeof AuthedScriptsRouteWithChildren
  '/about': typeof UnauthedAboutRoute
  '/login': typeof UnauthedLoginRoute
  '/logout': typeof UnauthedLogoutRoute
  '/api/health': typeof ApiHealthRoute
  '/api/whoami': typeof ApiWhoamiRoute
  '/game/grim': typeof GameGrimRouteWithChildren
  '/games/$gameId': typeof GamesGameIdRoute
  '/auth/forgot-password': typeof AuthedAuthForgotPasswordRoute
  '/rooms/n': typeof AuthedRoomsNRoute
  '/scripts/n': typeof AuthedScriptsNRoute
  '/api/auth/forgot-password': typeof ApiAuthForgotPasswordRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/auth/settings': typeof ApiAuthSettingsRoute
  '/api/dev/grimoire': typeof ApiDevGrimoireRoute
  '/game/grim/window': typeof GameGrimWindowRoute
  '/rooms/': typeof AuthedRoomsIndexRoute
  '/api/invites/': typeof ApiInvitesIndexRoute
  '/api/rooms/': typeof ApiRoomsIndexRoute
  '/api/scripts/': typeof ApiScriptsIndexRoute
  '/api/auth/me/mod': typeof ApiAuthMeModRoute
  '/api/games/$gameId/host': typeof ApiGamesGameIdHostRoute
  '/api/games/$gameId/ready': typeof ApiGamesGameIdReadyRoute
  '/api/games/$gameId/start-setup': typeof ApiGamesGameIdStartSetupRoute
  '/api/games/$gameId/storytellers': typeof ApiGamesGameIdStorytellersRoute
  '/api/games/$gameId/whispers': typeof ApiGamesGameIdWhispersRoute
  '/api/invites/$inviteId/accept': typeof ApiInvitesInviteIdAcceptRoute
  '/api/invites/$inviteId/cancel': typeof ApiInvitesInviteIdCancelRoute
  '/api/invites/$inviteId/reject': typeof ApiInvitesInviteIdRejectRoute
  '/api/matches/$matchId/phase': typeof ApiMatchesMatchIdPhaseRoute
  '/api/matches/$matchId/travel-approve': typeof ApiMatchesMatchIdTravelApproveRoute
  '/api/matches/$matchId/travel-deny': typeof ApiMatchesMatchIdTravelDenyRoute
  '/api/matches/$matchId/travel-request': typeof ApiMatchesMatchIdTravelRequestRoute
  '/api/rooms/$roomId/empty-seat': typeof ApiRoomsRoomIdEmptySeatRoute
  '/api/rooms/$roomId/invites': typeof ApiRoomsRoomIdInvitesRoute
  '/api/rooms/$roomId/match': typeof ApiRoomsRoomIdMatchRoute
  '/api/rooms/$roomId/remove-player': typeof ApiRoomsRoomIdRemovePlayerRoute
  '/api/rooms/$roomId/script': typeof ApiRoomsRoomIdScriptRoute
  '/api/rooms/$roomId/start-match': typeof ApiRoomsRoomIdStartMatchRoute
  '/api/matches/$matchId/': typeof ApiMatchesMatchIdIndexRoute
  '/api/rooms/$roomId/': typeof ApiRoomsRoomIdIndexRoute
  '/rooms/$roomId': typeof AuthedRoomsRoomRoomIdStRouteWithChildren
  '/rooms/$roomId/': typeof AuthedRoomsRoomRoomIdIndexRoute
  '/rooms/$roomId/window': typeof AuthedRoomsRoomRoomIdStWindowRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthedIndexRoute
  '/game': typeof GameRouteWithChildren
  '/scripts': typeof AuthedScriptsRouteWithChildren
  '/about': typeof UnauthedAboutRoute
  '/login': typeof UnauthedLoginRoute
  '/logout': typeof UnauthedLogoutRoute
  '/api/health': typeof ApiHealthRoute
  '/api/whoami': typeof ApiWhoamiRoute
  '/game/grim': typeof GameGrimRouteWithChildren
  '/games/$gameId': typeof GamesGameIdRoute
  '/auth/forgot-password': typeof AuthedAuthForgotPasswordRoute
  '/rooms/n': typeof AuthedRoomsNRoute
  '/scripts/n': typeof AuthedScriptsNRoute
  '/api/auth/forgot-password': typeof ApiAuthForgotPasswordRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/auth/settings': typeof ApiAuthSettingsRoute
  '/api/dev/grimoire': typeof ApiDevGrimoireRoute
  '/game/grim/window': typeof GameGrimWindowRoute
  '/rooms': typeof AuthedRoomsIndexRoute
  '/api/invites': typeof ApiInvitesIndexRoute
  '/api/rooms': typeof ApiRoomsIndexRoute
  '/api/scripts': typeof ApiScriptsIndexRoute
  '/api/auth/me/mod': typeof ApiAuthMeModRoute
  '/api/games/$gameId/host': typeof ApiGamesGameIdHostRoute
  '/api/games/$gameId/ready': typeof ApiGamesGameIdReadyRoute
  '/api/games/$gameId/start-setup': typeof ApiGamesGameIdStartSetupRoute
  '/api/games/$gameId/storytellers': typeof ApiGamesGameIdStorytellersRoute
  '/api/games/$gameId/whispers': typeof ApiGamesGameIdWhispersRoute
  '/api/invites/$inviteId/accept': typeof ApiInvitesInviteIdAcceptRoute
  '/api/invites/$inviteId/cancel': typeof ApiInvitesInviteIdCancelRoute
  '/api/invites/$inviteId/reject': typeof ApiInvitesInviteIdRejectRoute
  '/api/matches/$matchId/phase': typeof ApiMatchesMatchIdPhaseRoute
  '/api/matches/$matchId/travel-approve': typeof ApiMatchesMatchIdTravelApproveRoute
  '/api/matches/$matchId/travel-deny': typeof ApiMatchesMatchIdTravelDenyRoute
  '/api/matches/$matchId/travel-request': typeof ApiMatchesMatchIdTravelRequestRoute
  '/api/rooms/$roomId/empty-seat': typeof ApiRoomsRoomIdEmptySeatRoute
  '/api/rooms/$roomId/invites': typeof ApiRoomsRoomIdInvitesRoute
  '/api/rooms/$roomId/match': typeof ApiRoomsRoomIdMatchRoute
  '/api/rooms/$roomId/remove-player': typeof ApiRoomsRoomIdRemovePlayerRoute
  '/api/rooms/$roomId/script': typeof ApiRoomsRoomIdScriptRoute
  '/api/rooms/$roomId/start-match': typeof ApiRoomsRoomIdStartMatchRoute
  '/api/matches/$matchId': typeof ApiMatchesMatchIdIndexRoute
  '/api/rooms/$roomId': typeof ApiRoomsRoomIdIndexRoute
  '/rooms/$roomId': typeof AuthedRoomsRoomRoomIdIndexRoute
  '/rooms/$roomId/window': typeof AuthedRoomsRoomRoomIdStWindowRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/_unauthed': typeof UnauthedRouteWithChildren
  '/game': typeof GameRouteWithChildren
  '/_authed/scripts': typeof AuthedScriptsRouteWithChildren
  '/_unauthed/about': typeof UnauthedAboutRoute
  '/_unauthed/login': typeof UnauthedLoginRoute
  '/_unauthed/logout': typeof UnauthedLogoutRoute
  '/api/health': typeof ApiHealthRoute
  '/api/whoami': typeof ApiWhoamiRoute
  '/game/grim': typeof GameGrimRouteWithChildren
  '/games/$gameId': typeof GamesGameIdRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/auth/forgot-password': typeof AuthedAuthForgotPasswordRoute
  '/_authed/rooms/n': typeof AuthedRoomsNRoute
  '/_authed/scripts/n': typeof AuthedScriptsNRoute
  '/api/auth/forgot-password': typeof ApiAuthForgotPasswordRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/auth/settings': typeof ApiAuthSettingsRoute
  '/api/dev/grimoire': typeof ApiDevGrimoireRoute
  '/game/grim/window': typeof GameGrimWindowRoute
  '/_authed/rooms/': typeof AuthedRoomsIndexRoute
  '/api/invites/': typeof ApiInvitesIndexRoute
  '/api/rooms/': typeof ApiRoomsIndexRoute
  '/api/scripts/': typeof ApiScriptsIndexRoute
  '/api/auth/me/mod': typeof ApiAuthMeModRoute
  '/api/games/$gameId/host': typeof ApiGamesGameIdHostRoute
  '/api/games/$gameId/ready': typeof ApiGamesGameIdReadyRoute
  '/api/games/$gameId/start-setup': typeof ApiGamesGameIdStartSetupRoute
  '/api/games/$gameId/storytellers': typeof ApiGamesGameIdStorytellersRoute
  '/api/games/$gameId/whispers': typeof ApiGamesGameIdWhispersRoute
  '/api/invites/$inviteId/accept': typeof ApiInvitesInviteIdAcceptRoute
  '/api/invites/$inviteId/cancel': typeof ApiInvitesInviteIdCancelRoute
  '/api/invites/$inviteId/reject': typeof ApiInvitesInviteIdRejectRoute
  '/api/matches/$matchId/phase': typeof ApiMatchesMatchIdPhaseRoute
  '/api/matches/$matchId/travel-approve': typeof ApiMatchesMatchIdTravelApproveRoute
  '/api/matches/$matchId/travel-deny': typeof ApiMatchesMatchIdTravelDenyRoute
  '/api/matches/$matchId/travel-request': typeof ApiMatchesMatchIdTravelRequestRoute
  '/api/rooms/$roomId/empty-seat': typeof ApiRoomsRoomIdEmptySeatRoute
  '/api/rooms/$roomId/invites': typeof ApiRoomsRoomIdInvitesRoute
  '/api/rooms/$roomId/match': typeof ApiRoomsRoomIdMatchRoute
  '/api/rooms/$roomId/remove-player': typeof ApiRoomsRoomIdRemovePlayerRoute
  '/api/rooms/$roomId/script': typeof ApiRoomsRoomIdScriptRoute
  '/api/rooms/$roomId/start-match': typeof ApiRoomsRoomIdStartMatchRoute
  '/api/matches/$matchId/': typeof ApiMatchesMatchIdIndexRoute
  '/api/rooms/$roomId/': typeof ApiRoomsRoomIdIndexRoute
  '/_authed/rooms/_room/$roomId/_st': typeof AuthedRoomsRoomRoomIdStRouteWithChildren
  '/_authed/rooms/_room/$roomId/': typeof AuthedRoomsRoomRoomIdIndexRoute
  '/_authed/rooms/_room/$roomId/_st/window': typeof AuthedRoomsRoomRoomIdStWindowRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/game'
    | '/scripts'
    | '/about'
    | '/login'
    | '/logout'
    | '/api/health'
    | '/api/whoami'
    | '/game/grim'
    | '/games/$gameId'
    | '/auth/forgot-password'
    | '/rooms/n'
    | '/scripts/n'
    | '/api/auth/forgot-password'
    | '/api/auth/logout'
    | '/api/auth/register'
    | '/api/auth/settings'
    | '/api/dev/grimoire'
    | '/game/grim/window'
    | '/rooms/'
    | '/api/invites/'
    | '/api/rooms/'
    | '/api/scripts/'
    | '/api/auth/me/mod'
    | '/api/games/$gameId/host'
    | '/api/games/$gameId/ready'
    | '/api/games/$gameId/start-setup'
    | '/api/games/$gameId/storytellers'
    | '/api/games/$gameId/whispers'
    | '/api/invites/$inviteId/accept'
    | '/api/invites/$inviteId/cancel'
    | '/api/invites/$inviteId/reject'
    | '/api/matches/$matchId/phase'
    | '/api/matches/$matchId/travel-approve'
    | '/api/matches/$matchId/travel-deny'
    | '/api/matches/$matchId/travel-request'
    | '/api/rooms/$roomId/empty-seat'
    | '/api/rooms/$roomId/invites'
    | '/api/rooms/$roomId/match'
    | '/api/rooms/$roomId/remove-player'
    | '/api/rooms/$roomId/script'
    | '/api/rooms/$roomId/start-match'
    | '/api/matches/$matchId/'
    | '/api/rooms/$roomId/'
    | '/rooms/$roomId'
    | '/rooms/$roomId/'
    | '/rooms/$roomId/window'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/game'
    | '/scripts'
    | '/about'
    | '/login'
    | '/logout'
    | '/api/health'
    | '/api/whoami'
    | '/game/grim'
    | '/games/$gameId'
    | '/auth/forgot-password'
    | '/rooms/n'
    | '/scripts/n'
    | '/api/auth/forgot-password'
    | '/api/auth/logout'
    | '/api/auth/register'
    | '/api/auth/settings'
    | '/api/dev/grimoire'
    | '/game/grim/window'
    | '/rooms'
    | '/api/invites'
    | '/api/rooms'
    | '/api/scripts'
    | '/api/auth/me/mod'
    | '/api/games/$gameId/host'
    | '/api/games/$gameId/ready'
    | '/api/games/$gameId/start-setup'
    | '/api/games/$gameId/storytellers'
    | '/api/games/$gameId/whispers'
    | '/api/invites/$inviteId/accept'
    | '/api/invites/$inviteId/cancel'
    | '/api/invites/$inviteId/reject'
    | '/api/matches/$matchId/phase'
    | '/api/matches/$matchId/travel-approve'
    | '/api/matches/$matchId/travel-deny'
    | '/api/matches/$matchId/travel-request'
    | '/api/rooms/$roomId/empty-seat'
    | '/api/rooms/$roomId/invites'
    | '/api/rooms/$roomId/match'
    | '/api/rooms/$roomId/remove-player'
    | '/api/rooms/$roomId/script'
    | '/api/rooms/$roomId/start-match'
    | '/api/matches/$matchId'
    | '/api/rooms/$roomId'
    | '/rooms/$roomId'
    | '/rooms/$roomId/window'
  id:
    | '__root__'
    | '/_authed'
    | '/_unauthed'
    | '/game'
    | '/_authed/scripts'
    | '/_unauthed/about'
    | '/_unauthed/login'
    | '/_unauthed/logout'
    | '/api/health'
    | '/api/whoami'
    | '/game/grim'
    | '/games/$gameId'
    | '/_authed/'
    | '/_authed/auth/forgot-password'
    | '/_authed/rooms/n'
    | '/_authed/scripts/n'
    | '/api/auth/forgot-password'
    | '/api/auth/logout'
    | '/api/auth/register'
    | '/api/auth/settings'
    | '/api/dev/grimoire'
    | '/game/grim/window'
    | '/_authed/rooms/'
    | '/api/invites/'
    | '/api/rooms/'
    | '/api/scripts/'
    | '/api/auth/me/mod'
    | '/api/games/$gameId/host'
    | '/api/games/$gameId/ready'
    | '/api/games/$gameId/start-setup'
    | '/api/games/$gameId/storytellers'
    | '/api/games/$gameId/whispers'
    | '/api/invites/$inviteId/accept'
    | '/api/invites/$inviteId/cancel'
    | '/api/invites/$inviteId/reject'
    | '/api/matches/$matchId/phase'
    | '/api/matches/$matchId/travel-approve'
    | '/api/matches/$matchId/travel-deny'
    | '/api/matches/$matchId/travel-request'
    | '/api/rooms/$roomId/empty-seat'
    | '/api/rooms/$roomId/invites'
    | '/api/rooms/$roomId/match'
    | '/api/rooms/$roomId/remove-player'
    | '/api/rooms/$roomId/script'
    | '/api/rooms/$roomId/start-match'
    | '/api/matches/$matchId/'
    | '/api/rooms/$roomId/'
    | '/_authed/rooms/_room/$roomId/_st'
    | '/_authed/rooms/_room/$roomId/'
    | '/_authed/rooms/_room/$roomId/_st/window'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  UnauthedRoute: typeof UnauthedRouteWithChildren
  GameRoute: typeof GameRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  ApiWhoamiRoute: typeof ApiWhoamiRoute
  GamesGameIdRoute: typeof GamesGameIdRoute
  ApiAuthForgotPasswordRoute: typeof ApiAuthForgotPasswordRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthRegisterRoute: typeof ApiAuthRegisterRoute
  ApiAuthSettingsRoute: typeof ApiAuthSettingsRoute
  ApiDevGrimoireRoute: typeof ApiDevGrimoireRoute
  ApiInvitesIndexRoute: typeof ApiInvitesIndexRoute
  ApiRoomsIndexRoute: typeof ApiRoomsIndexRoute
  ApiScriptsIndexRoute: typeof ApiScriptsIndexRoute
  ApiAuthMeModRoute: typeof ApiAuthMeModRoute
  ApiGamesGameIdHostRoute: typeof ApiGamesGameIdHostRoute
  ApiGamesGameIdReadyRoute: typeof ApiGamesGameIdReadyRoute
  ApiGamesGameIdStartSetupRoute: typeof ApiGamesGameIdStartSetupRoute
  ApiGamesGameIdStorytellersRoute: typeof ApiGamesGameIdStorytellersRoute
  ApiGamesGameIdWhispersRoute: typeof ApiGamesGameIdWhispersRoute
  ApiInvitesInviteIdAcceptRoute: typeof ApiInvitesInviteIdAcceptRoute
  ApiInvitesInviteIdCancelRoute: typeof ApiInvitesInviteIdCancelRoute
  ApiInvitesInviteIdRejectRoute: typeof ApiInvitesInviteIdRejectRoute
  ApiMatchesMatchIdPhaseRoute: typeof ApiMatchesMatchIdPhaseRoute
  ApiMatchesMatchIdTravelApproveRoute: typeof ApiMatchesMatchIdTravelApproveRoute
  ApiMatchesMatchIdTravelDenyRoute: typeof ApiMatchesMatchIdTravelDenyRoute
  ApiMatchesMatchIdTravelRequestRoute: typeof ApiMatchesMatchIdTravelRequestRoute
  ApiRoomsRoomIdEmptySeatRoute: typeof ApiRoomsRoomIdEmptySeatRoute
  ApiRoomsRoomIdInvitesRoute: typeof ApiRoomsRoomIdInvitesRoute
  ApiRoomsRoomIdMatchRoute: typeof ApiRoomsRoomIdMatchRoute
  ApiRoomsRoomIdRemovePlayerRoute: typeof ApiRoomsRoomIdRemovePlayerRoute
  ApiRoomsRoomIdScriptRoute: typeof ApiRoomsRoomIdScriptRoute
  ApiRoomsRoomIdStartMatchRoute: typeof ApiRoomsRoomIdStartMatchRoute
  ApiMatchesMatchIdIndexRoute: typeof ApiMatchesMatchIdIndexRoute
  ApiRoomsRoomIdIndexRoute: typeof ApiRoomsRoomIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unauthed': {
      id: '/_unauthed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof UnauthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/games/$gameId': {
      id: '/games/$gameId'
      path: '/games/$gameId'
      fullPath: '/games/$gameId'
      preLoaderRoute: typeof GamesGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/grim': {
      id: '/game/grim'
      path: '/grim'
      fullPath: '/game/grim'
      preLoaderRoute: typeof GameGrimRouteImport
      parentRoute: typeof GameRoute
    }
    '/api/whoami': {
      id: '/api/whoami'
      path: '/api/whoami'
      fullPath: '/api/whoami'
      preLoaderRoute: typeof ApiWhoamiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unauthed/logout': {
      id: '/_unauthed/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof UnauthedLogoutRouteImport
      parentRoute: typeof UnauthedRoute
    }
    '/_unauthed/login': {
      id: '/_unauthed/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof UnauthedLoginRouteImport
      parentRoute: typeof UnauthedRoute
    }
    '/_unauthed/about': {
      id: '/_unauthed/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof UnauthedAboutRouteImport
      parentRoute: typeof UnauthedRoute
    }
    '/_authed/scripts': {
      id: '/_authed/scripts'
      path: '/scripts'
      fullPath: '/scripts'
      preLoaderRoute: typeof AuthedScriptsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/scripts/': {
      id: '/api/scripts/'
      path: '/api/scripts'
      fullPath: '/api/scripts/'
      preLoaderRoute: typeof ApiScriptsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rooms/': {
      id: '/api/rooms/'
      path: '/api/rooms'
      fullPath: '/api/rooms/'
      preLoaderRoute: typeof ApiRoomsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/invites/': {
      id: '/api/invites/'
      path: '/api/invites'
      fullPath: '/api/invites/'
      preLoaderRoute: typeof ApiInvitesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/rooms/': {
      id: '/_authed/rooms/'
      path: '/rooms'
      fullPath: '/rooms/'
      preLoaderRoute: typeof AuthedRoomsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/game/grim/window': {
      id: '/game/grim/window'
      path: '/window'
      fullPath: '/game/grim/window'
      preLoaderRoute: typeof GameGrimWindowRouteImport
      parentRoute: typeof GameGrimRoute
    }
    '/api/dev/grimoire': {
      id: '/api/dev/grimoire'
      path: '/api/dev/grimoire'
      fullPath: '/api/dev/grimoire'
      preLoaderRoute: typeof ApiDevGrimoireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/settings': {
      id: '/api/auth/settings'
      path: '/api/auth/settings'
      fullPath: '/api/auth/settings'
      preLoaderRoute: typeof ApiAuthSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/register': {
      id: '/api/auth/register'
      path: '/api/auth/register'
      fullPath: '/api/auth/register'
      preLoaderRoute: typeof ApiAuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/forgot-password': {
      id: '/api/auth/forgot-password'
      path: '/api/auth/forgot-password'
      fullPath: '/api/auth/forgot-password'
      preLoaderRoute: typeof ApiAuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/scripts/n': {
      id: '/_authed/scripts/n'
      path: '/n'
      fullPath: '/scripts/n'
      preLoaderRoute: typeof AuthedScriptsNRouteImport
      parentRoute: typeof AuthedScriptsRoute
    }
    '/_authed/rooms/n': {
      id: '/_authed/rooms/n'
      path: '/rooms/n'
      fullPath: '/rooms/n'
      preLoaderRoute: typeof AuthedRoomsNRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/auth/forgot-password': {
      id: '/_authed/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthedAuthForgotPasswordRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/rooms/$roomId/': {
      id: '/api/rooms/$roomId/'
      path: '/api/rooms/$roomId'
      fullPath: '/api/rooms/$roomId/'
      preLoaderRoute: typeof ApiRoomsRoomIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/matches/$matchId/': {
      id: '/api/matches/$matchId/'
      path: '/api/matches/$matchId'
      fullPath: '/api/matches/$matchId/'
      preLoaderRoute: typeof ApiMatchesMatchIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rooms/$roomId/start-match': {
      id: '/api/rooms/$roomId/start-match'
      path: '/api/rooms/$roomId/start-match'
      fullPath: '/api/rooms/$roomId/start-match'
      preLoaderRoute: typeof ApiRoomsRoomIdStartMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rooms/$roomId/script': {
      id: '/api/rooms/$roomId/script'
      path: '/api/rooms/$roomId/script'
      fullPath: '/api/rooms/$roomId/script'
      preLoaderRoute: typeof ApiRoomsRoomIdScriptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rooms/$roomId/remove-player': {
      id: '/api/rooms/$roomId/remove-player'
      path: '/api/rooms/$roomId/remove-player'
      fullPath: '/api/rooms/$roomId/remove-player'
      preLoaderRoute: typeof ApiRoomsRoomIdRemovePlayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rooms/$roomId/match': {
      id: '/api/rooms/$roomId/match'
      path: '/api/rooms/$roomId/match'
      fullPath: '/api/rooms/$roomId/match'
      preLoaderRoute: typeof ApiRoomsRoomIdMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rooms/$roomId/invites': {
      id: '/api/rooms/$roomId/invites'
      path: '/api/rooms/$roomId/invites'
      fullPath: '/api/rooms/$roomId/invites'
      preLoaderRoute: typeof ApiRoomsRoomIdInvitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rooms/$roomId/empty-seat': {
      id: '/api/rooms/$roomId/empty-seat'
      path: '/api/rooms/$roomId/empty-seat'
      fullPath: '/api/rooms/$roomId/empty-seat'
      preLoaderRoute: typeof ApiRoomsRoomIdEmptySeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/matches/$matchId/travel-request': {
      id: '/api/matches/$matchId/travel-request'
      path: '/api/matches/$matchId/travel-request'
      fullPath: '/api/matches/$matchId/travel-request'
      preLoaderRoute: typeof ApiMatchesMatchIdTravelRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/matches/$matchId/travel-deny': {
      id: '/api/matches/$matchId/travel-deny'
      path: '/api/matches/$matchId/travel-deny'
      fullPath: '/api/matches/$matchId/travel-deny'
      preLoaderRoute: typeof ApiMatchesMatchIdTravelDenyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/matches/$matchId/travel-approve': {
      id: '/api/matches/$matchId/travel-approve'
      path: '/api/matches/$matchId/travel-approve'
      fullPath: '/api/matches/$matchId/travel-approve'
      preLoaderRoute: typeof ApiMatchesMatchIdTravelApproveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/matches/$matchId/phase': {
      id: '/api/matches/$matchId/phase'
      path: '/api/matches/$matchId/phase'
      fullPath: '/api/matches/$matchId/phase'
      preLoaderRoute: typeof ApiMatchesMatchIdPhaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/invites/$inviteId/reject': {
      id: '/api/invites/$inviteId/reject'
      path: '/api/invites/$inviteId/reject'
      fullPath: '/api/invites/$inviteId/reject'
      preLoaderRoute: typeof ApiInvitesInviteIdRejectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/invites/$inviteId/cancel': {
      id: '/api/invites/$inviteId/cancel'
      path: '/api/invites/$inviteId/cancel'
      fullPath: '/api/invites/$inviteId/cancel'
      preLoaderRoute: typeof ApiInvitesInviteIdCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/invites/$inviteId/accept': {
      id: '/api/invites/$inviteId/accept'
      path: '/api/invites/$inviteId/accept'
      fullPath: '/api/invites/$inviteId/accept'
      preLoaderRoute: typeof ApiInvitesInviteIdAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/games/$gameId/whispers': {
      id: '/api/games/$gameId/whispers'
      path: '/api/games/$gameId/whispers'
      fullPath: '/api/games/$gameId/whispers'
      preLoaderRoute: typeof ApiGamesGameIdWhispersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/games/$gameId/storytellers': {
      id: '/api/games/$gameId/storytellers'
      path: '/api/games/$gameId/storytellers'
      fullPath: '/api/games/$gameId/storytellers'
      preLoaderRoute: typeof ApiGamesGameIdStorytellersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/games/$gameId/start-setup': {
      id: '/api/games/$gameId/start-setup'
      path: '/api/games/$gameId/start-setup'
      fullPath: '/api/games/$gameId/start-setup'
      preLoaderRoute: typeof ApiGamesGameIdStartSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/games/$gameId/ready': {
      id: '/api/games/$gameId/ready'
      path: '/api/games/$gameId/ready'
      fullPath: '/api/games/$gameId/ready'
      preLoaderRoute: typeof ApiGamesGameIdReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/games/$gameId/host': {
      id: '/api/games/$gameId/host'
      path: '/api/games/$gameId/host'
      fullPath: '/api/games/$gameId/host'
      preLoaderRoute: typeof ApiGamesGameIdHostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me/mod': {
      id: '/api/auth/me/mod'
      path: '/api/auth/me/mod'
      fullPath: '/api/auth/me/mod'
      preLoaderRoute: typeof ApiAuthMeModRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/rooms/_room/$roomId/': {
      id: '/_authed/rooms/_room/$roomId/'
      path: '/rooms/$roomId'
      fullPath: '/rooms/$roomId/'
      preLoaderRoute: typeof AuthedRoomsRoomRoomIdIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/rooms/_room/$roomId/_st': {
      id: '/_authed/rooms/_room/$roomId/_st'
      path: '/rooms/$roomId'
      fullPath: '/rooms/$roomId'
      preLoaderRoute: typeof AuthedRoomsRoomRoomIdStRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/rooms/_room/$roomId/_st/window': {
      id: '/_authed/rooms/_room/$roomId/_st/window'
      path: '/window'
      fullPath: '/rooms/$roomId/window'
      preLoaderRoute: typeof AuthedRoomsRoomRoomIdStWindowRouteImport
      parentRoute: typeof AuthedRoomsRoomRoomIdStRoute
    }
  }
}

interface AuthedScriptsRouteChildren {
  AuthedScriptsNRoute: typeof AuthedScriptsNRoute
}

const AuthedScriptsRouteChildren: AuthedScriptsRouteChildren = {
  AuthedScriptsNRoute: AuthedScriptsNRoute,
}

const AuthedScriptsRouteWithChildren = AuthedScriptsRoute._addFileChildren(
  AuthedScriptsRouteChildren,
)

interface AuthedRoomsRoomRoomIdStRouteChildren {
  AuthedRoomsRoomRoomIdStWindowRoute: typeof AuthedRoomsRoomRoomIdStWindowRoute
}

const AuthedRoomsRoomRoomIdStRouteChildren: AuthedRoomsRoomRoomIdStRouteChildren =
  {
    AuthedRoomsRoomRoomIdStWindowRoute: AuthedRoomsRoomRoomIdStWindowRoute,
  }

const AuthedRoomsRoomRoomIdStRouteWithChildren =
  AuthedRoomsRoomRoomIdStRoute._addFileChildren(
    AuthedRoomsRoomRoomIdStRouteChildren,
  )

interface AuthedRouteChildren {
  AuthedScriptsRoute: typeof AuthedScriptsRouteWithChildren
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedAuthForgotPasswordRoute: typeof AuthedAuthForgotPasswordRoute
  AuthedRoomsNRoute: typeof AuthedRoomsNRoute
  AuthedRoomsIndexRoute: typeof AuthedRoomsIndexRoute
  AuthedRoomsRoomRoomIdStRoute: typeof AuthedRoomsRoomRoomIdStRouteWithChildren
  AuthedRoomsRoomRoomIdIndexRoute: typeof AuthedRoomsRoomRoomIdIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedScriptsRoute: AuthedScriptsRouteWithChildren,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedAuthForgotPasswordRoute: AuthedAuthForgotPasswordRoute,
  AuthedRoomsNRoute: AuthedRoomsNRoute,
  AuthedRoomsIndexRoute: AuthedRoomsIndexRoute,
  AuthedRoomsRoomRoomIdStRoute: AuthedRoomsRoomRoomIdStRouteWithChildren,
  AuthedRoomsRoomRoomIdIndexRoute: AuthedRoomsRoomRoomIdIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface UnauthedRouteChildren {
  UnauthedAboutRoute: typeof UnauthedAboutRoute
  UnauthedLoginRoute: typeof UnauthedLoginRoute
  UnauthedLogoutRoute: typeof UnauthedLogoutRoute
}

const UnauthedRouteChildren: UnauthedRouteChildren = {
  UnauthedAboutRoute: UnauthedAboutRoute,
  UnauthedLoginRoute: UnauthedLoginRoute,
  UnauthedLogoutRoute: UnauthedLogoutRoute,
}

const UnauthedRouteWithChildren = UnauthedRoute._addFileChildren(
  UnauthedRouteChildren,
)

interface GameGrimRouteChildren {
  GameGrimWindowRoute: typeof GameGrimWindowRoute
}

const GameGrimRouteChildren: GameGrimRouteChildren = {
  GameGrimWindowRoute: GameGrimWindowRoute,
}

const GameGrimRouteWithChildren = GameGrimRoute._addFileChildren(
  GameGrimRouteChildren,
)

interface GameRouteChildren {
  GameGrimRoute: typeof GameGrimRouteWithChildren
}

const GameRouteChildren: GameRouteChildren = {
  GameGrimRoute: GameGrimRouteWithChildren,
}

const GameRouteWithChildren = GameRoute._addFileChildren(GameRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  UnauthedRoute: UnauthedRouteWithChildren,
  GameRoute: GameRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  ApiWhoamiRoute: ApiWhoamiRoute,
  GamesGameIdRoute: GamesGameIdRoute,
  ApiAuthForgotPasswordRoute: ApiAuthForgotPasswordRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthRegisterRoute: ApiAuthRegisterRoute,
  ApiAuthSettingsRoute: ApiAuthSettingsRoute,
  ApiDevGrimoireRoute: ApiDevGrimoireRoute,
  ApiInvitesIndexRoute: ApiInvitesIndexRoute,
  ApiRoomsIndexRoute: ApiRoomsIndexRoute,
  ApiScriptsIndexRoute: ApiScriptsIndexRoute,
  ApiAuthMeModRoute: ApiAuthMeModRoute,
  ApiGamesGameIdHostRoute: ApiGamesGameIdHostRoute,
  ApiGamesGameIdReadyRoute: ApiGamesGameIdReadyRoute,
  ApiGamesGameIdStartSetupRoute: ApiGamesGameIdStartSetupRoute,
  ApiGamesGameIdStorytellersRoute: ApiGamesGameIdStorytellersRoute,
  ApiGamesGameIdWhispersRoute: ApiGamesGameIdWhispersRoute,
  ApiInvitesInviteIdAcceptRoute: ApiInvitesInviteIdAcceptRoute,
  ApiInvitesInviteIdCancelRoute: ApiInvitesInviteIdCancelRoute,
  ApiInvitesInviteIdRejectRoute: ApiInvitesInviteIdRejectRoute,
  ApiMatchesMatchIdPhaseRoute: ApiMatchesMatchIdPhaseRoute,
  ApiMatchesMatchIdTravelApproveRoute: ApiMatchesMatchIdTravelApproveRoute,
  ApiMatchesMatchIdTravelDenyRoute: ApiMatchesMatchIdTravelDenyRoute,
  ApiMatchesMatchIdTravelRequestRoute: ApiMatchesMatchIdTravelRequestRoute,
  ApiRoomsRoomIdEmptySeatRoute: ApiRoomsRoomIdEmptySeatRoute,
  ApiRoomsRoomIdInvitesRoute: ApiRoomsRoomIdInvitesRoute,
  ApiRoomsRoomIdMatchRoute: ApiRoomsRoomIdMatchRoute,
  ApiRoomsRoomIdRemovePlayerRoute: ApiRoomsRoomIdRemovePlayerRoute,
  ApiRoomsRoomIdScriptRoute: ApiRoomsRoomIdScriptRoute,
  ApiRoomsRoomIdStartMatchRoute: ApiRoomsRoomIdStartMatchRoute,
  ApiMatchesMatchIdIndexRoute: ApiMatchesMatchIdIndexRoute,
  ApiRoomsRoomIdIndexRoute: ApiRoomsRoomIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
